### ISSUE TITLE
Limited location permission breaks the app

### ISSUE THREAD

**Issue by Rigamix** [tommasoberlose/another-widget#53]
Hi,

When installing this app on my pixel 2 XL running the latest version of Android, it only gives me two options regarding the location settings: either never use my location or only use my location when actively using the app. 

Now that's a problem because that means that the weather will not update unless I open the app, which defeats the purpose.

Any way to give the option to use location at all times?

Thanks

![Screenshot_20200504-220752](https://user-images.githubusercontent.com/61121635/81013839-bfd41b00-8e53-11ea-968a-57e241d5c67e.png)

**Comment by tommasoberlose** [comment]
Fixed in the last beta update. Thank you for the feedback!

**Comment by Rigamix** [comment]
Great thank you!

Denis Bouyer

**Comment by Rigamix** [comment]
Hello,

I've tried to reinstall the app, making sure I was a beta tester and it
still doesn't give me the option to let the app access my location at all
times.

Thanks

Denis Bouyer
